name: Docker image CI
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        schedulers: ["gridengine", "slurm"]
    env:
      REGISTRY: ghcr.io
      GIT_COMMIT: 273f592
      NAME: sv-callers-${{ matrix.schedulers }}
      TAG: dev

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Docker image name
        run: |
          echo "IMG_NAME=${REGISTRY}/${GITHUB_REPOSITORY_OWNER,,}/${NAME}:${TAG}" >> ${GITHUB_ENV}
      - name: Build Docker image
        run: |
          docker build --build-arg GIT_COMMIT=$GIT_COMMIT -t $IMG_NAME $NAME
          docker images
      - name: Push Docker image to registry
        run: docker push $IMG_NAME
