name: Docker image CI
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        schedulers: ["gridengine", "slurm"]
    env:
      REGISTRY: ghcr.io
      NAME: sv-callers-${{ matrix.schedulers }}
      TAG: latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build . -f $NAME/Dockerfile -t $REGISTRY/${{ github.actor }}/$NAME:$TAG
          docker images
      - name: Push Docker image to registry
        run: docker push $REGISTRY/${{ github.repository_owner }}/$NAME:$TAG
